name = "Research Group"
license = "MIT"
licenselink = "https://github.com/wowchemy/starter-hugo-research-group/blob/main/LICENSE.md"
description = "The **Research Group Template** empowers your research group to easily create a beautiful website with a stunning homepage, news, academic publications, events, team profiles, and a contact form."
homepage = "https://github.com/wowchemy/starter-hugo-research-group"
demosite = "https://research-group.netlify.app/"
tags = ["academic",
        "university",
        "research",
        "publications",
        "widgets",
        "portfolio",
        "responsive",
        "clean",
        "company",
        "blog",
        "events",
        "minimal",
        "light",
        "dark",
        "multilingual",
        "landing page",
        "contact form",
        "mobile",
        "search",
        "presentation",
        "simple",
        "minimalist",
        "starter",
        "modern",
        "one page",
        "customizable",
        "technical",
        "slide"
        ]
features = ["page builder", "widgets", "themes", "search", "research publication system", "filterable portfolio",
            "blog", "create courses", "talks", "events", "slides", "gallery", "contact form"]

[author]
  name = "George Cushen"
  homepage = "https://georgecushen.com"

[params.slider]
  enable = true
  manual = false # Setting manual to true renders the slide selection to only those where the post has a slider=true option enabled
  num_features = 6 # The slider picks up the banner images from the N most recent posts, where num_features is N.
